web:
  build: .
  labels:
    - convox.port.443.protocol=tls
    - convox.port.443.proxy=true
  ports:
    - 80:4000
    - 443:4001
  links:
    - database
    - redis
redis:
  image: convox/redis
  ports:
    - 6379
database:
  image: convox/postgres
  labels:
    - convox.health.timeout=60
  ports:
    - 5432
  volumes:
    - /var/lib/postgresql/data
