web:
  build: .
  labels:
    - convox.port.443.protocol=tls
    - convox.port.443.proxy=true
  links:
    - database
  ports:
    - 80:4000
    - 443:4001
  environment:
    - REDIS_HOST
database:
  image: convox/postgres
  labels:
    - convox.health.timeout=60
  ports:
    - 5432
  volumes:
    - /var/lib/postgresql/data
